import { createFontMapping } from 'pptx-glimpse';

export const PPTX_UNIFIED_FONT = 'Noto Sans CJK SC';

export const PPTX_FONT_SOURCE_NAMES = [
  'Microsoft YaHei',
  'Microsoft YaHei UI',
  'Microsoft YaHei Light',
  '微软雅黑',
  'SimHei',
  '黑体',
  'SimSun',
  '宋体',
  'NSimSun',
  '新宋体',
  'DengXian',
  'DengXian Light',
  '等线',
  '等线 Light',
  'FangSong',
  '仿宋',
  'KaiTi',
  '楷体',
  'STKaiti',
  '华文楷体',
  'STSong',
  '华文宋体',
  'Microsoft JhengHei',
  '微软正黑体',
  'PingFang SC',
  'PingFang TC',
  '苹方',
  'Hiragino Sans GB',
  'STHeiti',
  'STHeiti Light',
  'STHeiti Medium',
  'Songti',
  'Kaiti SC',
  'Source Han Sans CN',
  'Source Han Sans SC',
  'Noto Sans CJK SC',
  'Noto Sans SC',
  'Alibaba PuHuiTi',
  'Alibaba PuHuiTi 3.0 105 Heavy',
  '阿里巴巴普惠体',
  '汉仪中黑 简',
  '汉仪黑 简',
  '汉仪楷体 简',
  '方正',
  '方正姚体',
  '方正舒体',
  'LiSu',
  '隶书',
  'YouYuan',
  '幼圆',
  'Yu Gothic',
  'Meiryo',
  'MS Gothic',
  'MS Mincho',
  'ＭＳ Ｐゴシック',
  '游ゴシック',
  '游明朝',
  'MS P明朝',
  'MS Pゴシック',
  'メイリオ',
  '3ds',
  '3ds Light',
  'Roboto Thin',
  'Ubuntu',
  'Wingdings',
  'Wingdings 3',
  'Arial Regular',
  'Helvetica Neue',
];

export function createPptxFontMapping() {
  return createFontMapping(
    Object.fromEntries(PPTX_FONT_SOURCE_NAMES.map((name) => [name, PPTX_UNIFIED_FONT])),
  );
}
