/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export declare class StealthKeyboardTap {
  constructor()
  /**
   * Engage the tap. Every keystroke fires `callback` with the captured
   * metadata; the foreground app does NOT receive the event.
   *
   * Returns:
   *   - `true` if the tap engaged.
   *   - `false` if Accessibility permission is missing. Call
   *     `is_accessibility_granted()` and `request_accessibility_permission()`
   *     to drive the user through System Settings, then restart the app.
   *
   * Idempotent: repeated `start()` calls while active are no-ops.
   */
  start(callback: ((err: Error | null, arg: CapturedKey) => any)): boolean
  /**
   * Disengage the tap. After this returns, the next keystroke will
   * reach the foreground app normally. Safe to call multiple times.
   */
  stop(): void
  /**
   * True while the tap is engaged. Use to drive UI state ("stealth
   * typing" badge, mode indicator, etc.).
   */
  get isActive(): boolean
}

export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

/**
 * Apply stealth attributes to the BrowserWindow whose native handle is
 * passed in.
 *
 * `handle` is the buffer returned by `BrowserWindow.getNativeWindowHandle()`.
 * On macOS that buffer contains a single pointer to the BrowserWindow's
 * content `NSView`. We dereference to the parent `NSWindow` and apply the
 * stealth attributes on it.
 *
 * Returns `Ok(())` on success, `Err(...)` if the handle is malformed or the
 * view has no associated window (e.g. window destroyed mid-call).
 */
export declare function applyStealthToWindow(handle: Buffer): void

export interface AudioDeviceInfo {
  id: string
  name: string
}

/**
 * Event payload delivered to the JS callback. Crossing the V8 boundary is
 * not free, so we keep this struct flat (no nested objects) and only include
 * fields the renderer actually needs.
 */
export interface CapturedKey {
  /**
   * HID virtual keycode (e.g. 36 = Return, 51 = Delete, 53 = Esc). Stable
   * across keyboard layouts; use for shortcut detection (Esc → exit mode).
   */
  keyCode: number
  /**
   * The characters this key would type, given the active keyboard layout
   * and any held dead keys. Empty string for non-printable keys (Esc,
   * arrows, modifiers alone). Multi-char for IME composition or
   * surrogate pairs.
   */
  chars: string
  /**
   * Raw CGEventFlags bitmask (cmd=1<<20, opt=1<<19, ctrl=1<<18,
   * shift=1<<17, capsLock=1<<16, fn=1<<23). Renderer can decode without
   * us pre-splitting into bools.
   */
  flags: number
  /**
   * True for keyDown, false for keyUp. flagsChanged events are converted
   * to keyDown=true (modifier press) or keyDown=false (modifier release)
   * by the worker.
   */
  isKeyDown: boolean
}

/**
 * Deactivates a Dodo Payments license activation instance.
 *
 * `instance_id` — the activation instance ID (e.g. "lki_xxx") returned at activation time.
 * This is stored in the encrypted license file and passed here to free the slot.
 *
 * Returns a Promise resolving to "OK" or "ERR:dodo:<reason>".
 * Network errors return "ERR:dodo:network:..." — callers should still remove the local license
 * file even on network failure (fail-safe: local removal always happens).
 */
export declare function deactivateDodoKey(licenseKey: string, instanceId: string): Promise<unknown>

/**
 * Returns the platform-native ID of the current default output device.
 * macOS: CoreAudio device UID. Windows: WASAPI device id (eMultimedia/eConsole role).
 * Empty string on error or unsupported platform.
 *
 * JS polls this every few seconds during an active meeting; when the value
 * changes, main.ts recreates SystemAudioCapture so the CoreAudio Tap follows
 * the new output route. Without this, switching output devices mid-meeting
 * (plug in headphones, swap AirPods, route to virtual cable) leaves the tap
 * bound to the original device, capturing silence.
 */
export declare function getDefaultOutputDeviceId(): string

/**
 * Returns a deterministic hardware fingerprint (SHA-256 hash of the machine UID).
 * This is used to lock license keys to a specific physical device.
 */
export declare function getHardwareId(): string

export declare function getInputDevices(): Array<AudioDeviceInfo>

export declare function getOutputDevices(): Array<AudioDeviceInfo>

/**
 * True if this process has Accessibility trust (required for CGEventTap).
 * Cheap; safe to poll from JS to drive UI state.
 */
export declare function isAccessibilityGranted(): boolean

/**
 * Validates an existing Dodo Payments license key against the live API.
 *
 * Used for periodic startup checks to detect server-side revocations.
 * Returns a Promise resolving to "OK", "REVOKED", or "ERR:dodo:...".
 * Network errors return "ERR:dodo:network:..." so callers can fail-open.
 */
export declare function validateDodoKey(licenseKey: string): Promise<unknown>

/**
 * Activates a Dodo Payments license key against the live API.
 *
 * `device_label` — first 32 chars of the HWID hash; passed as the `name` field so the
 * merchant can correlate activations to devices in the Dodo dashboard.
 *
 * Returns a Promise resolving to "OK:<instance_id>" on success, or "ERR:dodo:<reason>".
 * The HTTP call runs on a libuv worker thread to prevent blocking the Node.js event loop.
 */
export declare function verifyDodoKey(licenseKey: string, deviceLabel: string): Promise<unknown>

/**
 * Validates a Gumroad license key by calling the Gumroad Licenses API.
 * Returns a Promise that resolves to "OK" on success, or an error message string on failure.
 * The HTTP call runs on a libuv worker thread to prevent blocking the Node.js event loop.
 */
export declare function verifyGumroadKey(licenseKey: string): Promise<unknown>
