import { sanitizeSenseVoiceTerms } from './termCorrection';
import type { SenseVoiceTermEntry } from './types';

export const DEFAULT_SENSEVOICE_TERM_CORRECTIONS: SenseVoiceTermEntry[] = sanitizeSenseVoiceTerms([
  {
    id: 'industrial-mes-supplier',
    canonical: 'MES供应商',
    variants: ['麦供应商', '卖供应商'],
    enabled: true,
  },
  {
    id: 'industrial-mes-system',
    canonical: 'MES系统',
    variants: ['麦系统', '卖系统', 'M S系统', 'M E S系统'],
    enabled: true,
  },
  {
    id: 'industrial-mes',
    canonical: 'MES',
    variants: ['M E S'],
    enabled: true,
  },
  {
    id: 'industrial-plm',
    canonical: 'PLM',
    variants: ['皮诶勒姆', '批艾勒姆', '屁艾勒姆', '听阿勒姆', 'TA乐姆', 'P L M'],
    enabled: true,
  },
  {
    id: 'industrial-product-lifecycle-management',
    canonical: '产品生命周期管理',
    variants: ['产品声明周期管理', '产品生命周期管里', '产品生命周其管理'],
    enabled: true,
  },
  {
    id: 'industrial-qms',
    canonical: 'QMS',
    variants: ['Q M S', '扣艾姆艾斯'],
    enabled: true,
  },
  {
    id: 'industrial-quality-management-system',
    canonical: '质量管理系统',
    variants: ['质量管你系统', '质量管里系统', '质量关联系统'],
    enabled: true,
  },
  {
    id: 'industrial-erp',
    canonical: 'ERP',
    variants: ['E R P', '一二P', '一二批', '伊阿皮'],
    enabled: true,
  },
  {
    id: 'industrial-enterprise-resource-planning',
    canonical: '企业资源计划',
    variants: ['企业资源规划', '企业资源记划'],
    enabled: true,
  },
  {
    id: 'industrial-alm',
    canonical: 'ALM',
    variants: ['A L M'],
    enabled: true,
  },
  {
    id: 'industrial-application-lifecycle-management',
    canonical: '应用生命周期管理',
    variants: ['应用生命管理', '应用声明周期管理'],
    enabled: true,
  },
  {
    id: 'industrial-cad',
    canonical: 'CAD',
    variants: ['C A D', '卡的', '凯德'],
    enabled: true,
  },
  {
    id: 'industrial-cae',
    canonical: 'CAE',
    variants: ['C A E', 'C A 一'],
    enabled: true,
  },
  {
    id: 'industrial-cam',
    canonical: 'CAM',
    variants: ['C A M', '看姆'],
    enabled: true,
  },
  {
    id: 'industrial-creo',
    canonical: 'Creo',
    variants: ['克里奥', '克瑞欧', '可瑞欧'],
    enabled: true,
  },
  {
    id: 'industrial-ptc-creo',
    canonical: 'PTC Creo',
    variants: ['PTC克瑞欧', 'PTC可瑞欧', 'PTCCreo'],
    enabled: true,
  },
  {
    id: 'industrial-windchill',
    canonical: 'Windchill',
    variants: ['温彻', '温切尔', '温秋', '温球', '温桥', 'Wind Chill', 'Winchill', 'Win Chill'],
    enabled: true,
  },
  {
    id: 'industrial-ptc-windchill',
    canonical: 'PTC Windchill',
    variants: ['PTC温切尔', 'PTC温秋', 'PTC温球'],
    enabled: true,
  },
  {
    id: 'industrial-feigenbaum-qms',
    canonical: 'Feigenbaum QMS',
    variants: ['FeigenbaumQMS', '费根鲍姆QMS', '飞根鲍姆QMS', '费根宝姆QMS', '费根包姆QMS'],
    enabled: true,
  },
  {
    id: 'industrial-bom',
    canonical: 'BOM',
    variants: ['B O M', '包姆', '爆木', '波姆'],
    enabled: true,
  },
  {
    id: 'industrial-bill-of-materials',
    canonical: '物料清单',
    variants: ['物料亲单'],
    enabled: true,
  },
  {
    id: 'industrial-eco',
    canonical: 'ECO',
    variants: ['E C O', '一西欧'],
    enabled: true,
  },
  {
    id: 'industrial-engineering-change-order',
    canonical: '工程变更单',
    variants: ['工程变改单', '工程更改单', '工程变更胆'],
    enabled: true,
  },
  {
    id: 'industrial-ecr',
    canonical: 'ECR',
    variants: ['E C R'],
    enabled: true,
  },
  {
    id: 'industrial-engineering-change-request',
    canonical: '工程变更请求',
    variants: ['工程变更需求'],
    enabled: true,
  },
  {
    id: 'industrial-apqp',
    canonical: 'APQP',
    variants: ['A P Q P', 'AP QP', 'A P Q 批', '产品质量先期测划', '产品质量先期策化'],
    enabled: true,
  },
  {
    id: 'industrial-ppap',
    canonical: 'PPAP',
    variants: ['P P A P', '批批AP', 'PP APP'],
    enabled: true,
  },
  {
    id: 'industrial-spc',
    canonical: 'SPC',
    variants: ['S P C', 'SP See', '统计过层控制', '统计过程空制', '统计过程孔制'],
    enabled: true,
  },
  {
    id: 'industrial-fmea',
    canonical: 'FMEA',
    variants: ['F M E A', 'F M E 呀', 'F M E A分析'],
    enabled: true,
  },
  {
    id: 'industrial-mbd',
    canonical: 'MBD',
    variants: ['M B D', 'MBD模型'],
    enabled: true,
  },
  {
    id: 'industrial-cfd',
    canonical: 'CFD',
    variants: ['C F D', 'CFD防真'],
    enabled: true,
  },
  {
    id: 'industrial-fluid-simulation',
    canonical: '流体仿真',
    variants: ['流体防真', '流体方针'],
    enabled: true,
  },
  {
    id: 'industrial-fluid-dynamics-simulation',
    canonical: '流体力学仿真',
    variants: ['流体力学防真'],
    enabled: true,
  },
  {
    id: 'industrial-mechanical-simulation',
    canonical: '力学仿真',
    variants: ['力学防真'],
    enabled: true,
  },
  {
    id: 'industrial-structural-mechanical-simulation',
    canonical: '结构力学仿真',
    variants: ['结构力学防真'],
    enabled: true,
  },
  {
    id: 'industrial-structural-simulation',
    canonical: '结构仿真',
    variants: ['结构防真'],
    enabled: true,
  },
  {
    id: 'industrial-thermal-simulation',
    canonical: '热仿真',
    variants: ['热防真'],
    enabled: true,
  },
  {
    id: 'industrial-ai-agent',
    canonical: 'AI智能体',
    variants: ['A I智能体', 'AI Agent', 'AI代理'],
    enabled: true,
  },
  {
    id: 'industrial-agent',
    canonical: '智能体',
    variants: ['智能替', '智能提'],
    enabled: true,
  },
  {
    id: 'industrial-knowledge-base',
    canonical: '知识库',
    variants: ['知识哭', '知识酷'],
    enabled: true,
  },
  {
    id: 'industrial-workflow',
    canonical: '工作流',
    variants: ['工作留', 'Work Flow', 'workflow'],
    enabled: true,
  },
  {
    id: 'industrial-po',
    canonical: 'PO',
    variants: ['P O', '皮欧', '批欧'],
    enabled: true,
  },
  {
    id: 'industrial-po-order',
    canonical: 'PO单',
    variants: ['皮欧单', '批欧单', 'P O单'],
    enabled: true,
  },
  {
    id: 'industrial-purchase-po',
    canonical: '采购PO',
    variants: ['采购P哦', '采购皮欧'],
    enabled: true,
  },
  {
    id: 'industrial-so',
    canonical: 'SO',
    variants: ['S O', '艾斯欧'],
    enabled: true,
  },
  {
    id: 'industrial-so-order',
    canonical: 'SO单',
    variants: ['艾斯欧单', 'S O单'],
    enabled: true,
  },
  {
    id: 'industrial-sales-so',
    canonical: '销售SO',
    variants: ['销售S哦', '销售艾斯欧', '销售皮欧'],
    enabled: true,
  },
  {
    id: 'industrial-ncr',
    canonical: 'NCR',
    variants: ['恩西阿', '恩C阿', 'N C R'],
    enabled: true,
  },
  {
    id: 'industrial-nonconformance-report',
    canonical: '不合格报告',
    variants: ['不合格抱告'],
    enabled: true,
  },
  {
    id: 'industrial-nonconformance-review-form',
    canonical: '不合格评审单',
    variants: ['不合格评审丹'],
    enabled: true,
  },
  {
    id: 'industrial-capa',
    canonical: 'CAPA',
    variants: ['卡帕', '卡怕', 'C A P A'],
    enabled: true,
  },
  {
    id: 'industrial-corrective-preventive-action',
    canonical: '纠正预防措施',
    variants: ['纠正预防错失', '纠正鱼防措施'],
    enabled: true,
  },
  {
    id: 'industrial-sop',
    canonical: 'SOP',
    variants: ['艾斯欧批', 'S O 批', 'S O P'],
    enabled: true,
  },
  {
    id: 'industrial-standard-operating-procedure',
    canonical: '标准作业程序',
    variants: ['标准作业程需', '标准作业呈序'],
    enabled: true,
  },
  {
    id: 'industrial-ecn',
    canonical: 'ECN',
    variants: ['一西恩', 'E C N'],
    enabled: true,
  },
  {
    id: 'industrial-engineering-change-notice',
    canonical: '工程变更通知',
    variants: ['工程变更通之', '工程变更同知'],
    enabled: true,
  },
  {
    id: 'industrial-engineering-change-notice-form',
    canonical: '工程变更通知单',
    variants: ['工程变更通知丹'],
    enabled: true,
  },
  {
    id: 'industrial-fai',
    canonical: 'FAI',
    variants: ['F A 一', 'F A I'],
    enabled: true,
  },
  {
    id: 'industrial-first-article-inspection',
    canonical: '首件检验',
    variants: ['首见检验', '手件检验', '首件减验'],
    enabled: true,
  },
  {
    id: 'industrial-production-part-approval-process',
    canonical: '生产件批准程序',
    variants: ['生产件批准程需', '生产件批淮程序'],
    enabled: true,
  },
  {
    id: 'industrial-cpk',
    canonical: 'CPK',
    variants: ['西皮K', 'C P K'],
    enabled: true,
  },
  {
    id: 'industrial-cpk-value',
    canonical: 'CPK值',
    variants: ['CPK只'],
    enabled: true,
  },
  {
    id: 'industrial-process-capability-index',
    canonical: '过程能力指数',
    variants: ['过程能立指数'],
    enabled: true,
  },
  {
    id: 'industrial-oee',
    canonical: 'OEE',
    variants: ['欧一一', 'O E E'],
    enabled: true,
  },
  {
    id: 'industrial-equipment-effectiveness',
    canonical: '设备综合效率',
    variants: ['设备综合小率', '设备宗合效率'],
    enabled: true,
  },
  {
    id: 'industrial-equipment-utilization',
    canonical: '设备稼动率',
    variants: ['设备嫁动率'],
    enabled: true,
  },
  {
    id: 'industrial-kpi',
    canonical: 'KPI',
    variants: ['K派', 'K P I'],
    enabled: true,
  },
  {
    id: 'industrial-key-performance-indicator',
    canonical: '关键绩效指标',
    variants: ['关键绩效只标', '关健绩效指标'],
    enabled: true,
  },
  {
    id: 'industrial-performance-indicator',
    canonical: '绩效指标',
    variants: ['绩效只标'],
    enabled: true,
  },
  {
    id: 'industrial-sla',
    canonical: 'SLA',
    variants: ['S L A', '艾斯艾勒A'],
    enabled: true,
  },
  {
    id: 'industrial-service-level-agreement',
    canonical: '服务等级协议',
    variants: ['服务等级协义', '服务等级协一'],
    enabled: true,
  },
  {
    id: 'industrial-crm',
    canonical: 'CRM',
    variants: ['C R M'],
    enabled: true,
  },
  {
    id: 'industrial-customer-relationship-management',
    canonical: '客户关系管理',
    variants: ['客户关系管里', '客户关西管理'],
    enabled: true,
  },
  {
    id: 'industrial-srm',
    canonical: 'SRM',
    variants: ['S R M'],
    enabled: true,
  },
  {
    id: 'industrial-supplier-relationship-management',
    canonical: '供应商关系管理',
    variants: ['供应商关西管理', '供应商关系管里'],
    enabled: true,
  },
  {
    id: 'industrial-ats',
    canonical: 'ATS',
    variants: ['A T S', '诶提艾斯'],
    enabled: true,
  },
  {
    id: 'industrial-candidate-tracking-system',
    canonical: '候选人跟踪系统',
    variants: ['候选人追踪系通', '候选人跟中系统'],
    enabled: true,
  },
  {
    id: 'industrial-jd',
    canonical: 'JD',
    variants: ['J D'],
    enabled: true,
  },
  {
    id: 'industrial-job-description',
    canonical: '职位描述',
    variants: ['职位描术', '职位苗述'],
    enabled: true,
  },
  {
    id: 'industrial-arr',
    canonical: 'ARR',
    variants: ['A R R'],
    enabled: true,
  },
  {
    id: 'industrial-annual-recurring-revenue',
    canonical: '年度经常性收入',
    variants: ['年度经常性收路'],
    enabled: true,
  },
  {
    id: 'industrial-mrr',
    canonical: 'MRR',
    variants: ['M R R'],
    enabled: true,
  },
  {
    id: 'industrial-monthly-recurring-revenue',
    canonical: '月度经常性收入',
    variants: ['月度经常性收路'],
    enabled: true,
  },
  {
    id: 'industrial-roi',
    canonical: 'ROI',
    variants: ['R O I'],
    enabled: true,
  },
  {
    id: 'industrial-return-on-investment',
    canonical: '投资回报率',
    variants: ['投资回抱率', '投资回报绿'],
    enabled: true,
  },
  {
    id: 'industrial-ar',
    canonical: 'AR',
    variants: ['A R'],
    enabled: true,
  },
  {
    id: 'industrial-accounts-receivable',
    canonical: '应收账款',
    variants: ['应收帐款', '应收胀款', '应收张款'],
    enabled: true,
  },
  {
    id: 'industrial-ap',
    canonical: 'AP',
    variants: ['A P'],
    enabled: true,
  },
  {
    id: 'industrial-accounts-payable',
    canonical: '应付账款',
    variants: ['应付帐款', '应付胀款', '应付张款'],
    enabled: true,
  },
  {
    id: 'industrial-catia',
    canonical: 'CATIA',
    variants: ['卡提亚', '卡蒂亚', '卡提呀', 'CAT IA', '卡T亚'],
    enabled: true,
  },
  {
    id: 'industrial-solidworks',
    canonical: 'SolidWorks',
    variants: ['索利德沃克斯', '骚立德沃克斯', 'Solid Work', 'Solidworks', '索力德Works'],
    enabled: true,
  },
  {
    id: 'industrial-teamcenter',
    canonical: 'Teamcenter',
    variants: ['Team Center', '听森特', '提姆森特', 'T森特'],
    enabled: true,
  },
  {
    id: 'industrial-siemens-teamcenter',
    canonical: 'Siemens Teamcenter',
    variants: ['西门子听森特'],
    enabled: true,
  },
  {
    id: 'industrial-enovia',
    canonical: 'Enovia',
    variants: ['伊诺维亚', '依诺维亚', '一诺维亚', 'Eno Via'],
    enabled: true,
  },
  {
    id: 'industrial-dassault-enovia',
    canonical: 'Dassault Enovia',
    variants: ['达索伊诺维亚'],
    enabled: true,
  },
  {
    id: 'industrial-3dexperience',
    canonical: '3DEXPERIENCE',
    variants: ['三D体验', '3D Experience', '三D Experience', '三DEXPERIENCE'],
    enabled: true,
  },
  {
    id: 'industrial-dassault-3dexperience',
    canonical: 'Dassault 3DEXPERIENCE',
    variants: ['达索三D体验'],
    enabled: true,
  },
  {
    id: 'industrial-nx',
    canonical: 'NX',
    variants: ['恩艾克斯', 'N X'],
    enabled: true,
  },
  {
    id: 'industrial-ug-nx',
    canonical: 'UG NX',
    variants: ['UG恩艾克斯'],
    enabled: true,
  },
  {
    id: 'industrial-siemens-nx',
    canonical: 'Siemens NX',
    variants: ['西门子恩艾克斯'],
    enabled: true,
  },
  {
    id: 'industrial-autoform',
    canonical: 'AutoForm',
    variants: ['奥拓Form', '奥特Form', 'Auto From', 'Auto Phone'],
    enabled: true,
  },
  {
    id: 'industrial-sap',
    canonical: 'SAP',
    variants: ['撒普', 'S A P'],
    enabled: true,
  },
  {
    id: 'industrial-sap-s4hana',
    canonical: 'SAP S/4HANA',
    variants: ['SAP四哈娜', 'S4哈娜'],
    enabled: true,
  },
  {
    id: 'industrial-oracle',
    canonical: 'Oracle',
    variants: ['奥瑞克', '欧瑞克'],
    enabled: true,
  },
  {
    id: 'industrial-oracle-ebs',
    canonical: 'Oracle EBS',
    variants: ['Oracle一比艾斯', 'Oracle E B S', '甲骨文EBS'],
    enabled: true,
  },
  {
    id: 'industrial-kingdee',
    canonical: '金蝶',
    variants: ['金碟', 'King Dee'],
    enabled: true,
  },
  {
    id: 'industrial-yonyou',
    canonical: '用友',
    variants: ['用有', '用油', 'Yonyou'],
    enabled: true,
  },
  {
    id: 'industrial-siemens-opcenter',
    canonical: 'Siemens Opcenter',
    variants: ['西门子Op森特', '西门子Op Center', 'Siemens欧普森特'],
    enabled: true,
  },
  {
    id: 'industrial-opcenter',
    canonical: 'Opcenter',
    variants: ['欧普森特'],
    enabled: true,
  },
  {
    id: 'industrial-aras',
    canonical: 'Aras',
    variants: ['阿拉斯', '阿瑞斯'],
    enabled: true,
  },
  {
    id: 'industrial-aegis',
    canonical: 'Aegis',
    variants: ['伊吉斯', '艾吉斯'],
    enabled: true,
  },
  {
    id: 'industrial-part-design',
    canonical: 'Part Design',
    variants: ['Part迪赛', '帕特Design', '派的Design'],
    enabled: true,
  },
  {
    id: 'industrial-assembly-design',
    canonical: 'Assembly Design',
    variants: ['Assembly迪赛', '阿森布里Design', '装配Design'],
    enabled: true,
  },
  {
    id: 'industrial-gsd',
    canonical: 'GSD',
    variants: ['G S D', '鸡艾斯D'],
    enabled: true,
  },
  {
    id: 'industrial-dmu',
    canonical: 'DMU',
    variants: ['D M U', 'D M you'],
    enabled: true,
  },
  {
    id: 'industrial-fti',
    canonical: 'FTI',
    variants: ['F T 一', 'F T I'],
    enabled: true,
  },
  {
    id: 'industrial-knowledgeware',
    canonical: 'Knowledgeware',
    variants: ['Knowledge Ware', 'Knowledge Where'],
    enabled: true,
  },
  {
    id: 'industrial-sheet-metal',
    canonical: 'Sheet Metal',
    variants: ['Sheetmetal', 'Sheet Medal'],
    enabled: true,
  },
  {
    id: 'industrial-weldment',
    canonical: 'Weldment',
    variants: ['Weld Ment'],
    enabled: true,
  },
  {
    id: 'industrial-drafting-module',
    canonical: 'Drafting模块',
    variants: ['抓图模块', 'Drafting摸块'],
    enabled: true,
  },
  {
    id: 'industrial-pdmlink',
    canonical: 'PDMLink',
    variants: ['PDM Link', 'PD M Link', 'P D M Link'],
    enabled: true,
  },
  {
    id: 'industrial-mpmlink',
    canonical: 'MPMLink',
    variants: ['MPM Link', 'M P M Link'],
    enabled: true,
  },
  {
    id: 'industrial-projectlink',
    canonical: 'ProjectLink',
    variants: ['Project Link'],
    enabled: true,
  },
  {
    id: 'industrial-ipd',
    canonical: 'IPD',
    variants: ['I P D'],
    enabled: true,
  },
  {
    id: 'industrial-integrated-product-development',
    canonical: '集成产品开发',
    variants: ['集成产品发开', '集成产品开法', '集成产品开发展'],
    enabled: true,
  },
  {
    id: 'industrial-pdt',
    canonical: 'PDT经理',
    variants: ['P D T经理','PTT经理','PDD经理'],
    enabled: true,
  },
  {
    id: 'industrial-tr-review',
    canonical: 'TR评审',
    variants: ['TR凭审', '技术凭审', '技术平审'],
    enabled: true,
  },
  {
    id: 'industrial-dcp',
    canonical: 'DCP',
    variants: ['D C P'],
    enabled: true,
  },
  {
    id: 'industrial-dcp-review-point',
    canonical: '决策评审点',
    variants: ['决策凭审点', '决策平审点'],
    enabled: true,
  },
  {
    id: 'industrial-charter',
    canonical: 'Charter',
    variants: ['恰特', '恰特儿'],
    enabled: true,
  },
  {
    id: 'industrial-pmt',
    canonical: 'PMT',
    variants: ['P M T'],
    enabled: true,
  },
  {
    id: 'industrial-sp-bp',
    canonical: 'SP/BP',
    variants: ['S P B P', 'SP BP', 'SP和B批'],
    enabled: true,
  },
  {
    id: 'industrial-fmea-failure-analysis',
    canonical: '失效模式分析',
    variants: ['失效摸式分析'],
    enabled: true,
  },
  {
    id: 'industrial-dfmea',
    canonical: 'DFMEA',
    variants: ['D F M E A', 'D F M E 呀'],
    enabled: true,
  },
  {
    id: 'industrial-pfmea',
    canonical: 'PFMEA',
    variants: ['P F M E A', 'P F M E 呀'],
    enabled: true,
  },
  {
    id: 'industrial-five-why',
    canonical: '5 Why',
    variants: ['Five Why', 'Five Wise'],
    enabled: true,
  },
  {
    id: 'industrial-fishbone',
    canonical: '鱼骨图',
    variants: ['鱼刺图', '鱼骨徒'],
    enabled: true,
  },
  {
    id: 'industrial-msa',
    canonical: 'MSA',
    variants: ['M S A'],
    enabled: true,
  },
  {
    id: 'industrial-measurement-system-analysis',
    canonical: '测量系统分析',
    variants: ['测量系通分析', '测量系统分西'],
    enabled: true,
  },
  {
    id: 'industrial-dfm',
    canonical: 'DFM',
    variants: ['D F M'],
    enabled: true,
  },
  {
    id: 'industrial-design-for-manufacturing',
    canonical: '可制造性设计',
    variants: ['可制造性设寄'],
    enabled: true,
  },
  {
    id: 'industrial-dfa',
    canonical: 'DFA',
    variants: ['D F A'],
    enabled: true,
  },
  {
    id: 'industrial-design-for-assembly',
    canonical: '可装配性设计',
    variants: ['可装配性设寄'],
    enabled: true,
  },
  {
    id: 'industrial-pipeline',
    canonical: 'Pipeline',
    variants: ['派普莱恩'],
    enabled: true,
  },
  {
    id: 'industrial-win-rate',
    canonical: 'Win Rate',
    variants: ['Win瑞特'],
    enabled: true,
  },
  {
    id: 'industrial-offer',
    canonical: 'Offer',
    variants: ['欧佛'],
    enabled: true,
  },
  {
    id: 'industrial-process-step',
    canonical: '工序',
    variants: ['工续', '工需'],
    enabled: true,
  },
  {
    id: 'industrial-station',
    canonical: '工位',
    variants: ['工为'],
    enabled: true,
  },
  {
    id: 'industrial-line',
    canonical: '产线',
    variants: ['产险', '产先'],
    enabled: true,
  },
  {
    id: 'industrial-first-piece',
    canonical: '首件',
    variants: ['手件', '首见'],
    enabled: true,
  },
  {
    id: 'industrial-last-piece',
    canonical: '末件',
    variants: ['末见', '末检件'],
    enabled: true,
  },
  {
    id: 'industrial-yield',
    canonical: '良率',
    variants: ['粮率', '量率', '良绿'],
    enabled: true,
  },
  {
    id: 'industrial-fpy',
    canonical: '直通率',
    variants: ['直通绿', '直通律', '直通虑'],
    enabled: true,
  },
  {
    id: 'industrial-rework',
    canonical: '返工',
    variants: ['反工', '返攻'],
    enabled: true,
  },
  {
    id: 'industrial-repair',
    canonical: '返修',
    variants: ['反修', '返休'],
    enabled: true,
  },
  {
    id: 'industrial-line-stop',
    canonical: '停线',
    variants: ['停显', '停先'],
    enabled: true,
  },
  {
    id: 'industrial-drawing',
    canonical: '图纸',
    variants: ['图子', '图质'],
    enabled: true,
  },
  {
    id: 'industrial-engineering-drawing',
    canonical: '工程图纸',
    variants: ['工程图子'],
    enabled: true,
  },
  {
    id: 'industrial-2d-drawing',
    canonical: '二维图',
    variants: ['二维图子', '二位图'],
    enabled: true,
  },
  {
    id: 'industrial-3d-drawing',
    canonical: '三维图',
    variants: ['三维图子', '三位图'],
    enabled: true,
  },
  {
    id: 'industrial-traceability',
    canonical: '追溯',
    variants: ['追朔', '追诉'],
    enabled: true,
  },
  {
    id: 'industrial-automation',
    canonical: '自动化',
    variants: ['自动画', '自动话'],
    enabled: true,
  },
]);

export function mergeSenseVoiceTermCorrections(userTerms: unknown): SenseVoiceTermEntry[] {
  const mergedByCanonical = new Map<string, SenseVoiceTermEntry>();

  for (const term of DEFAULT_SENSEVOICE_TERM_CORRECTIONS) {
    mergedByCanonical.set(term.canonical.toLowerCase(), term);
  }

  for (const term of sanitizeSenseVoiceTerms(userTerms)) {
    mergedByCanonical.set(term.canonical.toLowerCase(), term);
  }

  return [...mergedByCanonical.values()];
}
